version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/d1-bot
hooks:
  AfterInstall:
    - location: setup-docker.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: run.sh
      timeout: 300
      runas: ubuntu