version: '3'
services:
  app:
    command: sh entrypoint.sh
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: "postgres:13.2-alpine"
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres