version: '3'
services:
  app:
    command: python bot.py
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app