name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run isort
        run: |
          pip install isort==5.9.3
          python -m isort . --check
      - name: Run black
        run: |
          pip install black==22.3.0
          python -m black . --check
      - name: Run autoflake
        run: |
          pip install autoflake==1.4
          python -m autoflake --exclude=__init__.py \
            --remove-unused-variables --remove-all-unused-imports \
            --in-place --recursive $MODE --check .
      - name: Create Env File
        run: cp .env.dist .env
      - name: Install dependencies
        run: make build
      - name: Test with pytest
        run: make test

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [ continuous-integration ]
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETKEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Git_Application \
            --deployment-group-name development_gropup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
